// import 'reflect-metadata';
import { ReflectiveInjector } from 'injection-js';

import { FiveEDrsHelper, FiveEDrsSpellsInput, FiveEDrsSpellsMdOutput } from './5e-drs';
import { AideDdHelper, AideDdSpellsInput } from './aidedd';
import { AideDdSpellsMdOutput } from './aidedd/services/aide-dd-spells.md-output';
import {
  AssetsService,
  CacheService,
  ConfigService,
  HtmlElementHelper,
  LabelsHelper,
  NewPageService,
  provideAsInputService,
  provideAsOutputService,
  provideExitCleaner,
  UrlHelper,
} from './core';
import {
  DdbBackgroundsInput,
  DdbBackgroundsMdOutput,
  DdbFeatsInput,
  DdbFeatsMdOutput,
  DdbHelper,
  DdbItemsInput,
  DdbItemsMdOutput,
  DdbLinkHelper,
  DdbMagicItemsHelper,
  DdbMagicItemsInput,
  DdbMagicItemsMdOutput,
  DdbMdHelper,
  DdbMonstersInput,
  DdbMonstersMdOutput,
  DdbPlayerClassesInput,
  DdbPlayerClassesMdOutput,
  DdbSourcesHelper,
  DdbSourcesInput,
  DdbSourcesMdOutput,
  DdbSpeciesInput,
  DdbSpeciesMdOutput,
  DdbSpellsInput,
  DdbSpellsMdOutput,
} from './ddb';
import { ObsidianMdHelper } from './markdown-yaml';

export function getInjector() {
  return ReflectiveInjector.resolveAndCreate([
    AideDdHelper,
    AssetsService,
    CacheService,
    ConfigService,
    DdbHelper,
    DdbLinkHelper,
    DdbMdHelper,
    DdbSourcesHelper,
    FiveEDrsHelper,
    HtmlElementHelper,
    LabelsHelper,
    NewPageService,
    UrlHelper,
    DdbMagicItemsHelper,
    ObsidianMdHelper,
    provideAsInputService(AideDdSpellsInput),
    provideAsInputService(DdbBackgroundsInput),
    provideAsInputService(DdbFeatsInput),
    provideAsInputService(DdbItemsInput),
    provideAsInputService(DdbMagicItemsInput),
    provideAsInputService(DdbMonstersInput),
    provideAsInputService(DdbPlayerClassesInput),
    provideAsInputService(DdbSourcesInput),
    provideAsInputService(DdbSpeciesInput),
    provideAsInputService(DdbSpellsInput),
    provideAsInputService(FiveEDrsSpellsInput),
    provideAsOutputService(AideDdSpellsMdOutput),
    provideAsOutputService(DdbBackgroundsMdOutput),
    provideAsOutputService(DdbFeatsMdOutput),
    provideAsOutputService(DdbItemsMdOutput),
    provideAsOutputService(DdbMagicItemsMdOutput),
    provideAsOutputService(DdbMonstersMdOutput),
    provideAsOutputService(DdbPlayerClassesMdOutput),
    provideAsOutputService(DdbSourcesMdOutput),
    provideAsOutputService(DdbSpeciesMdOutput),
    provideAsOutputService(DdbSpellsMdOutput),
    provideAsOutputService(FiveEDrsSpellsMdOutput),
    provideExitCleaner(CacheService),
    provideExitCleaner(NewPageService),
  ]);
}
