export enum SpellProperties {
  NAME = "Name",
  LEVEL = "Level",
  SCHOOL = "School",
  CASTING_TIME = "Casting Time",
  RANGE_AREA = "Range (Area)",
  COMPONENTS = "Components",
  DURATION = "Duration",
  CONCENTRATION = "Concentration",
  RITUAL = "Ritual",
  ATTACK_SAVE = "Attack/Save",
  DAMAGE_EFFECT = "Damage/Effect",
  TAGS = "Tags",
  SPELL_LISTS = "Spell Lists",
  SOURCE = "Source",
  SOURCE_DETAILS = "Source Details",
  SAME_AS = "Same as",
  DATA_SOURCE = "Data Source",
  LANG = "Lang",
  ALT_NAMES = "Alt Names",
  URI = "URI",
  ID = "Id",
}
